### ISSUE TITLE
Configure UART DMA Idle interrupt

### ISSUE THREAD

**Issue by Sourland** [PeakSat-AUTH/comms-software#10]
Trigger an interrupt when the DMA UART is IDLE and:
Notifty the suspended TCHandling Task or use a handing FreeRTOS Queue for the task to fetch data only when the queue has content

**Comment by AndronikosKostas** [comment]
Δούλεψε με task notifications τελικά και όχι με ουρά. Με ουρά αργούσε, έχανε μηνύματα και δεν ήταν αξιόπιστο.
code .py

![Screenshot (1681)](https://github.com/PeakSat-AUTH/comms-software/assets/58566096/fa51ce2b-662c-474b-a78a-1f1b76f70291)

ISR 

![Screenshot (1679)](https://github.com/PeakSat-AUTH/comms-software/assets/58566096/52e49b69-e4ed-40ee-968f-79d9b6069630)

execute()

![Screenshot (1680)](https://github.com/PeakSat-AUTH/comms-software/assets/58566096/6407b703-3712-4ad9-9f2e-4ac8a7cdf1a4)

**Comment by AndronikosKostas** [comment]
RESULTS 

![Screenshot (1683)](https://github.com/PeakSat-AUTH/comms-software/assets/58566096/6ea9a112-9c8c-4ad8-b25e-6f5f354dd9aa)

ALSO DONT FORGET : 

    // disabling the half buffer interrupt
    __HAL_DMA_DISABLE_IT(&hdma_usart3_rx, DMA_IT_HT);
    // disabling the full buffer interrupt
    __HAL_DMA_DISABLE_IT(&hdma_usart3_rx, DMA_IT_TC);
