### ISSUE TITLE
Test the AT86RF215 configuration

### ISSUE THREAD

**Issue by Sourland** [PeakSat-AUTH/comms-software#11]
### Objective
Validate the configuration settings of the AT86RF215 transceiver for compliance with expected operational parameters.

### Test Parameters
- **Modulation**: FSK (Frequency-Shift Keying)
- **Frequency Range**: 400-403 MHz (subject to ITU negotiations)
- **Bandwidth**: 100 kHz
- **Data Rate**: 50 kbps

### Test Procedure
- [x] Verify the transceiver is correctly modulating the base signal as FSK.
- [x] Confirm the up-conversion process to the designated frequency range.
- [x] Measure the bandwidth and data rate to ensure they meet the specified requirements.
- [x] Test the signal integrity post power amplification.
- [x] Check the output through the filter for any anomalies before transmission via the antenna.

### Notes
- Ensure all tests are conducted in a controlled environment to simulate operational conditions.
- Document any deviations from the expected configuration for review.

**Comment by AndronikosKostas** [comment]
![IMG_4882](https://github.com/PeakSat-AUTH/comms-software/assets/58566096/e5c22bcb-0376-4cc3-a649-30983b133fd9)

**Comment by Sourland** [comment]
Settings confirmed, closing issue

**Comment by AndronikosKostas** [comment]
After further modification, we got better results by applying a modulation index of 1,  and direct modulation along with a pre-emphasis filter. Now we have a clear view of the symbol frequencies (fcarrier +- 25kHz) and they are in higher power levels very close to the carrier power. Also, the pre-emphasis filter along with the direct modulation decrease the power of all the unwanted peaks outside of the desired bandwidth. Finally, the Bandwidth is under 100kHz and close to 75kHz.

![with_preemphasis](https://github.com/PeakSat/comms-software/assets/58566096/cffb9096-895d-4159-a360-29effa8e2a90)
