### ISSUE TITLE
Create a GNSS Reception and Parsing Task

### ISSUE THREAD

**Issue by Sourland** [PeakSat-AUTH/comms-software#18]
### Objective
Develop a task within the FreeRTOS environment for the reception and parsing of GNSS data, ensuring data integrity and accurate parsing of NMEA sentences.

### Resources
- [GPSTask.c source code](https://gitlab.com/acubesat/obc/freertos-mockup/-/blob/GPS_Code_Test_Ready/Src/Tasks/GPSTask.c?ref_type=tags)
- [GPSTask.h header file](https://gitlab.com/acubesat/obc/freertos-mockup/-/blob/GPS_Code_Test_Ready/Inc/Tasks/GPSTask.h?ref_type=tags)
- [minmea Library](https://github.com/kosma/minmea)

### Acceptance Criteria
- [x] Task successfully initializes GNSS hardware and DMA channels.
- [x] Task can receive GNSS data via DMA.
- [ ] Task can parse NMEA sentences and update the system's GNSS related parameters.
- [ ] Task handles errors and edge cases gracefully.
- [ ] Integration tests verify task functionality.

**Comment by AndronikosKostas** [comment]
The remaining tasks will be added to the COMMS-SW repo
